import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { CompactionInvariants, CompactionEvaluation, HandoffResult } from "./types.ts";
import { recordAuditEvent } from "../audit.ts";

export const DEFAULT_CONTEXT_MAX_TOKENS = 200_000;
export const COMPACTION_THRESHOLD_PERCENT = 70;

/**
 * Evaluates current context usage against the 70% threshold invariant.
 */
export function evaluateContextUsage(
  usedTokens: number,
  maxTokens: number = DEFAULT_CONTEXT_MAX_TOKENS,
): CompactionEvaluation {
  const usagePercent = Math.round((usedTokens / maxTokens) * 100);
  const thresholdExceeded = usagePercent >= COMPACTION_THRESHOLD_PERCENT;

  const prompt = thresholdExceeded
    ? `Context at ${usagePercent}%. Compact now or continue?`
    : `Context at ${usagePercent}% used.`;

  return {
    usedTokens,
    maxTokens,
    usagePercent,
    thresholdExceeded,
    prompt,
  };
}

/**
 * Renders the 5 mandatory compaction invariants into canonical CURRENT.md format.
 */
export function renderCurrentMdContent(
  invariants: CompactionInvariants,
  options?: { agent?: string; sessionId?: string; project?: string },
): string {
  const timestamp = new Date().toISOString();
  const agent = options?.agent ?? "Muse";
  const lines: string[] = [
    "# 📍 Active Workspace Context & Invariants (CURRENT.md)",
    "",
    "> Auto-generated by MuseMemory Context Compaction & Session Handoff Engine",
    `> **Last Updated**: ${timestamp} | **Agent**: ${agent}`,
    "",
    "---",
    "",
    "## 🔒 1. Active Working Constraints & Invariants",
  ];

  const constraints = invariants.activeConstraints && invariants.activeConstraints.length > 0
    ? invariants.activeConstraints
    : ["Zero unmasked credentials committed (Vibeguard Protocol).", "Fail fast with explicit errors rather than swallowing failures."];

  for (const c of constraints) {
    lines.push(`- ${c}`);
  }

  lines.push("");
  lines.push("## 🎯 2. High-Level Goal");
  lines.push(invariants.highLevelGoal.trim());
  lines.push("");

  lines.push("## 🏗️ 3. Current Architecture & Data Flow");
  lines.push(invariants.currentArchitecture.trim());
  lines.push("");

  lines.push("## ✅ 4. Implemented & Done");
  if (invariants.completedTasks.length > 0) {
    for (const task of invariants.completedTasks) {
      lines.push(`- [x] ${task}`);
    }
  } else {
    lines.push("- None recorded yet.");
  }
  lines.push("");

  lines.push("## ⏳ 5. Explicitly Not Done Yet");
  if (invariants.openTasks.length > 0) {
    for (const task of invariants.openTasks) {
      lines.push(`- [ ] ${task}`);
    }
  } else {
    lines.push("- All planned tasks completed.");
  }
  lines.push("");

  lines.push("## 🚀 6. Next Concrete Task");
  lines.push(`> **Next Up**: ${invariants.nextConcreteTask.trim()}`);
  lines.push("");

  if (invariants.decisionsMade && invariants.decisionsMade.length > 0) {
    lines.push("## 💡 7. Key Decisions & Discoveries");
    for (const d of invariants.decisionsMade) {
      lines.push(`- ${d}`);
    }
    lines.push("");
  }

  lines.push("## 📜 8. Interruption-Proof Checkpoint & Session Handoff");
  lines.push(`- **Status**: IN-PROGRESS`);
  lines.push(`- **Timestamp**: ${timestamp}`);
  if (options?.sessionId) lines.push(`- **Session ID**: ${options.sessionId}`);
  lines.push(`- **Handoff Directive**: Next session starts by executing: "${invariants.nextConcreteTask.trim()}"`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Generates an ultra-compact resumption prompt injection string for the subsequent session.
 */
export function generateResumptionPrompt(invariants: CompactionInvariants): string {
  const parts: string[] = [
    `[SESSION HANDOFF RESUMPTION]`,
    `Goal: ${invariants.highLevelGoal}`,
    `Next Task: ${invariants.nextConcreteTask}`,
    `Completed: ${invariants.completedTasks.length} items | Pending: ${invariants.openTasks.length} items`,
  ];
  if (invariants.openTasks.length > 0) {
    parts.push(`Open: ${invariants.openTasks.slice(0, 3).join("; ")}`);
  }
  return parts.join("\n");
}

/**
 * Commits an interruption-proof checkpoint handoff into CURRENT.md.
 */
export function generateSessionHandoff(
  memoryDir: string,
  invariants: CompactionInvariants,
  options?: { agent?: string; sessionId?: string; project?: string },
): HandoffResult {
  if (!invariants.highLevelGoal || !invariants.nextConcreteTask) {
    throw new Error("Cannot generate handoff: highLevelGoal and nextConcreteTask are mandatory");
  }

  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true });
  }

  const currentMdPath = join(memoryDir, "CURRENT.md");
  const markdownContent = renderCurrentMdContent(invariants, options);
  writeFileSync(currentMdPath, markdownContent, "utf8");

  recordAuditEvent(memoryDir, {
    operation: "checkpoint" as any,
    entry_id: "CURRENT.md",
    project: options?.project ?? "workspace",
    actor: options?.agent ?? "compaction_engine",
    details: {
      nextTask: invariants.nextConcreteTask,
      completedCount: invariants.completedTasks.length,
      openCount: invariants.openTasks.length,
    },
  });

  const resumptionPrompt = generateResumptionPrompt(invariants);

  return {
    currentMdPath,
    invariants,
    markdownContent,
    resumptionPrompt,
    timestamp: new Date().toISOString(),
  };
}
