import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  readdirSync,
  statSync,
  renameSync,
  chmodSync,
} from "node:fs";
import { join, relative } from "node:path";
import type { Store } from "./store.ts";
import { importTranscript } from "./harvest.ts";
import { recordAuditEvent } from "./audit.ts";

const HOOK_SCRIPT = `#!/bin/sh
# musememory harvester hook (auto-generated by 'memory hook install --git')
memory harvest-auto >/dev/null 2>&1 || true
`;

export interface HookInstallResult {
  installed: boolean;
  path?: string;
  message: string;
}

/**
 * Install the post-turn harvester as a git pre-commit hook. Never clobbers an
 * existing hook; creates nothing beyond the hook file itself (the inbox is
 * created lazily on first harvest).
 */
export function installGitHook(workspaceRoot: string): HookInstallResult {
  const gitDir = join(workspaceRoot, ".git");
  if (!existsSync(gitDir)) {
    return { installed: false, message: `no .git directory in ${workspaceRoot} — run inside a git repository` };
  }
  const hooksDir = join(gitDir, "hooks");
  const hookPath = join(hooksDir, "pre-commit");
  if (existsSync(hookPath)) {
    return { installed: false, path: hookPath, message: `pre-commit hook already exists at ${hookPath} — leaving it untouched` };
  }
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(hookPath, HOOK_SCRIPT, "utf8");
  chmodSync(hookPath, 0o755);
  return { installed: true, path: hookPath, message: `installed pre-commit hook at ${hookPath}` };
}

export interface HarvestAutoResult {
  processed: { file: string; movedTo: string; imported: number }[];
  errors: string[];
  message: string;
}

/** Translate a simple glob (`*`, `**`, `?`) into a RegExp over relative paths. */
export function globToRegex(glob: string): RegExp {
  const escaped = glob
    .replace(/[.+^${}()|[\]\\]/g, "\\$&")
    .replace(/\*\*/g, "\0")
    .replace(/\*/g, "[^/]*")
    .replace(/\?/g, "[^/]")
    .replace(/\0/g, ".*");
  return new RegExp(`^${escaped}$`);
}

function walkFiles(dir: string, root: string, regex: RegExp, out: string[] = []): string[] {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (e.name === ".git" || e.name === "node_modules" || e.name === ".memory") continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      walkFiles(p, root, regex, out);
    } else if (regex.test(relative(root, p))) {
      out.push(p);
    }
  }
  return out;
}

function newestInboxJsonl(inboxDir: string): string | null {
  if (!existsSync(inboxDir)) return null;
  const files = readdirSync(inboxDir)
    .filter((f) => f.endsWith(".jsonl"))
    .map((f) => join(inboxDir, f))
    .filter((f) => statSync(f).isFile());
  if (files.length === 0) return null;
  return files.sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs)[0];
}

/**
 * Automated Post-Turn Transcript Harvester:
 * discovers transcript files (explicit glob wins, else newest *.jsonl in
 * `.memory/inbox/`), runs them through the harvest pipeline proposing units as
 * candidates (never auto-confirms), then moves processed files to
 * `.memory/inbox/processed/` and audit-logs each file. The inbox dir is only
 * created when a file actually needs moving.
 */
export function harvestAuto(
  store: Store,
  workspaceRoot: string,
  memoryDir: string,
  options: { from?: string; project?: string } = {},
): HarvestAutoResult {
  const result: HarvestAutoResult = { processed: [], errors: [], message: "" };

  let files: string[] = [];
  if (options.from) {
    files = walkFiles(workspaceRoot, workspaceRoot, globToRegex(options.from));
    if (files.length === 0) {
      result.message = `no files matched glob '${options.from}'`;
      return result;
    }
  } else {
    const inboxDir = join(memoryDir, "inbox");
    const newest = newestInboxJsonl(inboxDir);
    if (!newest) {
      result.message = "no transcripts waiting in .memory/inbox/";
      return result;
    }
    files = [newest];
  }

  const processedDir = join(memoryDir, "inbox", "processed");

  for (const file of files) {
    try {
      const content = readFileSync(file, "utf8");
      const res = importTranscript(store, content, {
        project: options.project ?? "inbox",
        confirmed: false,
        source: "harvest_auto",
      });

      mkdirSync(processedDir, { recursive: true }); // lazy: only when there is something to move
      const base = file.split("/").pop() ?? "transcript.jsonl";
      let dest = join(processedDir, base);
      if (existsSync(dest)) {
        dest = join(processedDir, base.replace(/\.jsonl$/, `_moved_${Date.now()}.jsonl`));
      }
      renameSync(file, dest);

      result.processed.push({ file, movedTo: dest, imported: res.imported });
      result.errors.push(...res.errors);
      recordAuditEvent(memoryDir, {
        operation: "transcript_import",
        entry_id: file,
        actor: "harvester",
        details: { imported: res.imported, moved_to: dest, source: "harvest-auto" },
      });
    } catch (err: unknown) {
      result.errors.push(`${file}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  result.message = `processed ${result.processed.length} transcript(s), ${result.processed.reduce((n, p) => n + p.imported, 0)} unit(s) proposed`;
  return result;
}
